export const data = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    course: 'Chemical Engineering',
    matriculation: 'CHE/123/456',
    phone: '08012345678',
    school: 'Kadpoly',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    course: 'Computer Science',
    matriculation: 'CSC/234/567',
    phone: '08023456789',
    school: 'Kadpoly',
  },
  {
    id: 3,
    firstName: 'Michael',
    lastName: 'Johnson',
    course: 'Electrical Engineering',
    matriculation: 'EEE/345/678',
    phone: '08034567890',
    school: 'Kadpoly',
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Williams',
    course: 'Mechanical Engineering',
    matriculation: 'MEC/456/789',
    phone: '08045678901',
    school: 'Kadpoly',
  },
  {
    id: 5,
    firstName: 'David',
    lastName: 'Brown',
    course: 'Civil Engineering',
    matriculation: 'CIV/567/890',
    phone: '08056789012',
    school: 'Kadpoly',
  },
  {
    id: 6,
    firstName: 'Sarah',
    lastName: 'Davis',
    course: 'Architecture',
    matriculation: 'ARC/678/901',
    phone: '08067890123',
    school: 'Kadpoly',
  },
  {
    id: 7,
    firstName: 'James',
    lastName: 'Miller',
    course: 'Physics',
    matriculation: 'PHY/789/012',
    phone: '08078901234',
    school: 'Kadpoly',
  },
  {
    id: 8,
    firstName: 'Olivia',
    lastName: 'Wilson',
    course: 'Mathematics',
    matriculation: 'MTH/890/123',
    phone: '08089012345',
    school: 'Kadpoly',
  },
  {
    id: 9,
    firstName: 'Daniel',
    lastName: 'Moore',
    course: 'Statistics',
    matriculation: 'STA/901/234',
    phone: '08090123456',
    school: 'Kadpoly',
  },
  {
    id: 10,
    firstName: 'Sophia',
    lastName: 'Taylor',
    course: 'Biochemistry',
    matriculation: 'BCH/012/345',
    phone: '08001234567',
    school: 'Kadpoly',
  },
];
